FROM centos:7

#add dinstall group
RUN groupadd dinstall && useradd -g dinstall -m -d /home/dmdba -s /bin/bash dmdba

#copy install files
ARG installFilesDir=/home/dmdba/install
ARG installConfName=setup.xml
COPY DMInstall.bin  ${installFilesDir}/
COPY ${installConfName} ${installFilesDir}/

# add gosu
RUN yum install -y wget && wget https://github.com/tianon/gosu/releases/download/1.11/gosu-arm64 \
    &&mv gosu-arm64 /usr/local/bin/gosu \
    &&chmod +x /usr/local/bin/gosu

#change user
USER dmdba

#prepare install diretory
RUN mkdir /home/dmdba/dmdbms

#execute silence install
RUN sh ${installFilesDir}/DMInstall.bin -q ${installFilesDir}/${installConfName}

USER root

#RUN /home/dmdba/dmdbms/script/root/root_installer.sh
RUN cp "/home/dmdba/dmdbms/bin/dm_svc.conf" /etc/dm_svc.conf
RUN chmod 6755 "/home/dmdba/dmdbms/bin/dminit" \
    && chmod 6755 "/home/dmdba/dmdbms/bin/dmserver" \
    && chown 0:0 "/home/dmdba/dmdbms/bin/dmcss" \
    && chmod 6755 "/home/dmdba/dmdbms/bin/dmcss"

#RUN "/home/dmdba/dmdbms/script/root/dm_service_installer.sh" -s "/home/dmdba/dmdbms/bin/DmAPService"
#RUN /home/dmdba/dmdbms/script/root/dm_service_installer.sh -t dmserver -p "Base" -i /home/dmdba/data/DAMENG/dm.ini

COPY docker-entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 5236

WORKDIR /home/dmdba

ENTRYPOINT ["docker-entrypoint.sh"]
